name: qudo-env2

channels:
  - defaults
dependencies:
  - python=3.7
  - conda-forge::pytest==6.2.4
  - pip
  - pip:
    - kmodes==0.11.1
    - quantipy3==0.2.9
    - Unidecode==1.3.2
    - tqdm==4.62.3
